version: '3.1'

services:

  redmine:
    image: redmine
    restart: always
    ports:
      - 8020:3000
    depends_on:
      - db
    environment:
      REDMINE_DB_MYSQL: db
      REDMINE_DB_DATABASE: redmine
      REDMINE_DB_USERNAME: redmine
      REDMINE_DB_PASSWORD: pakistan
      REDMINE_RELATIVE_URL_ROOT: /plane
      #REDMINE_DB_MYSQL: db
      #REDMINE_DB_PASSWORD: example
      REDMINE_SECRET_KEY_BASE: supersecretkey
    volumes:
      - ./config.rb:/usr/src/redmine/config/environment.rb
      # - ./config.ru:/usr/src/redmine/config.ru

  db:
    container_name: mariadb-container
    image: mariadb:latest
    restart: always
    environment:
      MYSQL_DATABASE: redmine
      MYSQL_USER: redmine
      MYSQL_PASSWORD: pakistan
      MYSQL_ROOT_PASSWORD: pakistan
