version: '3.1'

services:

  redmine:
    image: redmine
    restart: always
    ports:
      - 8020:3000
    environment:
      REDMINE_RELATIVE_URL_ROOT: /plane
      REDMINE_DB_MYSQL: db
      REDMINE_DB_PASSWORD: example
      REDMINE_SECRET_KEY_BASE: supersecretkey
    volumes:
      - ./config.rb:/usr/src/redmine/config/environment.rb
      - ./config.ru:/usr/src/redmine/config.ru

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: redmine